### ISSUE TITLE
Atomic version not being detected

### ISSUE THREAD

**Issue by christianh814** [myllynen/openshift-ha-load-balancer#2]
On Ansible 1.9.6; it wasn't detecting if it was "atomic" or not...changed the playbook to look like this

```
  tasks:
    - name: Detect Atomic Host
      stat:
        path: /dev/mapper/atomicos-root
      register: stat_result

    - name: Remove unhelpful packages
      yum: name={{ item }} state=absent
      with_items:
        - firewalld
        - firewalld-filesystem
      when: stat_result.stat.exists == False

    - name: Install needed packages
      yum: name={{ item }} state=installed
      with_items:
        - conntrack-tools
        - haproxy
        - iptables
        - iptables-services
        - ipvsadm
        - keepalived
        - rsyslog
      when: stat_result.stat.exists == False
```
